### ISSUE TITLE
make Design Layout

### ISSUE THREAD

**Issue by rikithreddy** [zer3f/SchoolMS#3]

**Comment by Hari-28** [comment]
![screenshot 39](https://cloud.githubusercontent.com/assets/24910968/22278613/e0530b6a-e2ea-11e6-8c0d-865cd1ef456e.png)
 ==> Typical Layout of login page



![screenshot 37](https://cloud.githubusercontent.com/assets/24910968/22278573/7ae7ba96-e2ea-11e6-8288-2c684e244916.png)
==> Example

**Comment by Hari-28** [comment]
Mention Changes if any!!
